#!/usr/bin/env bash
if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

diff_files=$(git diff-index --diff-filter=ACM --name-only "$against")
python_file_pattern='\.pyi\?$'
python_files=$(grep $python_file_pattern <<< $diff_files)

# Blacken code
python -m black -t py38 $python_files
black_code=$?

# Flake8
python -m flake8 --max-line-length 119 --config "./blog_backend/.flake8" $python_files
flake8_code=$?

# MyPy (only works when in project root directory)
project_python_files=$(cut -d '/' -f2- <<< $python_files)

# MyPy quirks when not receiving any argument, so skip it when no file's found.
if [[ "$project_python_files" == *[![:space:]]* ]]
then
  pushd blog_backend && {
    python -m mypy --config-file "./mypy.ini" $project_python_files; mypy_code=$?;
  } || popd || exit ;
fi

exit $(( black_code | flake8_code | mypy_code ))
